CREATE TABLE Employees
(
    Id                       INT IDENTITY(1,1) PRIMARY KEY,
    OrganizationId            INT NULL DEFAULT 1,
    EmpId                    VARCHAR(25) NOT NULL,
    Fullname                 VARCHAR(50) NOT NULL,
    Pic                      VARCHAR(2000) NULL,
    Phone                    VARCHAR(20) NOT NULL,
    Email                    VARCHAR(50) NULL,
    Cnic                     VARCHAR(20) NOT NULL,
    Address                  VARCHAR(255) NOT NULL,
    EmpType                  VARCHAR(20) NOT NULL,
    DepartmentId             INT NOT NULL,
    DesignationId            INT NOT NULL,
    ShiftId                  INT NOT NULL,
    LocationId               INT NOT NULL,
    ParentId                 INT NOT NULL DEFAULT 0,
    ExcludeFromAttendance    INT NOT NULL DEFAULT 0,
    IsActive                 INT NOT NULL DEFAULT 1,
    Gender                   VARCHAR(10) NULL,
    MaritalStatus            VARCHAR(20) NULL,
    DateOfBirth              DATE NULL,
    Mobile                   VARCHAR(20) NULL,
    City                     VARCHAR(100) NULL,
    Country                  VARCHAR(100) NULL,
    PostalCode               VARCHAR(20) NULL,
    HireDate                 DATE NULL,
    TerminationDate         DATE NULL,
    BasicSalary              DECIMAL(18, 2) DEFAULT 0,
    BankAccountId            INT NULL,
    BankAccountNumber       VARCHAR(50) NULL,
    EmergencyContactName     VARCHAR(100) NULL,
    EmergencyContactPhone    VARCHAR(20) NULL,
    EmergencyContactRelation VARCHAR(50) NULL,
    Notes                    VARCHAR(1000) NULL,
    CreatedBy                INT NULL,
    CreatedOn                DATETIME NOT NULL DEFAULT GETDATE(),
    CreatedFrom              VARCHAR(255) NULL,
    UpdatedBy                INT NULL,
    UpdatedOn                DATETIME NOT NULL DEFAULT GETDATE(),
    UpdatedFrom              VARCHAR(255) NULL,
    IsSoftDeleted            INT NULL DEFAULT 0,
    CONSTRAINT FK_Employees_Organization FOREIGN KEY (OrganizationId) REFERENCES Organizations(Id),
    CONSTRAINT FK_Employees_Shifts FOREIGN KEY (ShiftId) REFERENCES Shifts(Id),
    CONSTRAINT FK_Employees_Locations FOREIGN KEY (LocationId) REFERENCES Locations(Id),
    CONSTRAINT FK_Employees_Departments FOREIGN KEY (DepartmentId) REFERENCES Departments(Id),
    CONSTRAINT FK_Employees_Designations FOREIGN KEY (DesignationId) REFERENCES Designations(Id)
);


INSERT INTO Employees
(
    EmpId,
    Fullname,
    Phone,
    Cnic,
    Address,
    EmpType,
    DepartmentId,
    DesignationId,
    ShiftId,
    LocationId
)
VALUES
('00001', 'SYSTEM ADMINISTRATOR', '0000000000', '00000-0000000-0', 'Head Office, MOITT', 'PERMANENT', 1, 1, 1, 1),
('00002', 'AAMIR RASHID', '03008813444', '3740504520207', 'House # 700, Street # 33, Bahria Town Phase 5.', 'PERMANENT', 1, 1, 2, 1),
('00003', 'SHAH M TALHA TAHIR', '', '', '', 'PERMANENT', 1, 1, 2, 1),
('00004', 'DR MAHNOOR', '', '', '', 'PERMANENT', 3, 3, 2, 1),
('00005', 'ZUBAIR', '', '', '', 'PERMANENT', 1, 3, 2, 1),
('00006', 'HASNAIN ARSHAD', '', '', '', 'PERMANENT', 1, 3, 2, 1),
('00007', 'USMAN HABIB', '', '', '', 'PERMANENT', 1, 3, 2, 1),
('00008', 'TALHA KHAN', '', '', '', 'PERMANENT', 1, 3, 2, 1),
('00009', 'SADAM', '', '', '', 'PERMANENT', 1, 3, 2, 1);

