-- Create PettyCash Table
CREATE TABLE PettyCash
(
    Id                  INT              PRIMARY KEY IDENTITY(1,1),
    OrganizationId      INT             NOT NULL,
    SeqNo               VARCHAR(50)      NOT NULL,
    FileAttachment      VARCHAR(255),
    LocationId          INT,
    EmployeeId          INT,
    TranDate            DATE             NOT NULL,
    Description         VARCHAR(255)     NOT NULL,
    Amount              DECIMAL(10, 2)   NOT NULL,
    AccountId           INT,
    TranType            VARCHAR(20)      NOT NULL,
    PaymentMethod       VARCHAR(100)     NOT NULL,
    RefNo               VARCHAR(50),
    TranRef             VARCHAR(50),
	CreatedBy           INT             NULL DEFAULT NULL,
	CreatedOn           DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedFrom         VARCHAR(255)    NULL DEFAULT NULL,
	UpdatedBy           INT             NULL DEFAULT NULL,
	UpdatedOn           DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UpdatedFrom         VARCHAR(255)    NULL DEFAULT NULL,
    IsSoftDeleted       SMALLINT         NOT NULL DEFAULT 0,
    IsPostedToGL        SMALLINT         NOT NULL DEFAULT 0,
    PostedToGLDate      DATETIME        NULL,
    PostedToGLBy        INT             NULL,
    GLEntryNo           VARCHAR(50)     NULL,
    Guid                UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    BaseCurrencyId      INT             NULL,
    EnteredCurrencyId   INT             NULL,
    ExchangeRate        DECIMAL(18, 6)  NULL DEFAULT 1.0,
    RowVersion          VARBINARY(8)    NULL,

    CONSTRAINT FK_PettyCash_Location FOREIGN KEY (LocationId) REFERENCES Locations(Id),
    CONSTRAINT FK_PettyCash_CreatedBy FOREIGN KEY (CreatedBy) REFERENCES Users(Id),
    CONSTRAINT FK_PettyCash_UpdatedBy FOREIGN KEY (UpdatedBy) REFERENCES Users(Id),
    CONSTRAINT FK_PettyCash_Employee FOREIGN KEY (EmployeeId) REFERENCES Employees(Id),
    CONSTRAINT FK_PettyCash_Account FOREIGN KEY (AccountId) REFERENCES ChartOfAccounts(Id),
    CONSTRAINT FK_PettyCash_Organization FOREIGN KEY (OrganizationId) REFERENCES Organizations(Id),
    CONSTRAINT FK_PettyCash_PostedToGLBy FOREIGN KEY (PostedToGLBy) REFERENCES dbo.Users(Id),
    CONSTRAINT FK_PettyCash_BaseCurrency FOREIGN KEY (BaseCurrencyId) REFERENCES Currencies(Id),
    CONSTRAINT FK_PettyCash_EnteredCurrency FOREIGN KEY (EnteredCurrencyId) REFERENCES Currencies(Id)
);
