CREATE TABLE PartyDocuments
(
	Id					INT PRIMARY KEY IDENTITY(1,1),
	Guid				UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	PartyId				INT NOT NULL,
	DocumentType		VARCHAR(50) NOT NULL,   -- NTN / CNIC / GST / LICENSE / IMEI / GSM
	DocumentNumber		VARCHAR(50) NOT NULL,
	PercentageAmount	VARCHAR(100) NULL,
	IsActive            SMALLINT			NOT NULL DEFAULT 1,
	CreatedBy			INT					NULL DEFAULT NULL,
	CreatedOn           DATETIME			NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedFrom         VARCHAR(255)		NULL DEFAULT NULL,
	UpdatedBy           INT					NULL DEFAULT NULL,
	UpdatedOn           DATETIME			NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UpdatedFrom         VARCHAR(255)		NULL DEFAULT NULL,
	IsSoftDeleted       SMALLINT			NOT NULL DEFAULT 0,
	RowVersion          ROWVERSION,
	CONSTRAINT FK_PartyDocuments_Party FOREIGN KEY (PartyId) REFERENCES Parties(Id),
	CONSTRAINT FK_PartyDocuments_CreatedBy FOREIGN KEY (CreatedBy) REFERENCES Users(Id),
	CONSTRAINT FK_PartyDocuments_UpdatedBy FOREIGN KEY (UpdatedBy) REFERENCES Users(Id)
);

INSERT INTO PartyDocuments (PartyId, DocumentType, DocumentNumber)
SELECT Id, 'NTN', '1234567890' FROM Parties WHERE Name = 'S&S ENTERPRISES, KARACHI (210-4)'
UNION ALL
SELECT Id, 'CNIC', '4210112345671' FROM Parties WHERE Name = 'S&S ENTERPRISES, KARACHI (210-4)'
UNION ALL
SELECT Id, 'GST', 'GST123456789' FROM Parties WHERE Name = 'S&S ENTERPRISES, KARACHI (210-4)'
UNION ALL
SELECT Id, 'NTN', '9876543210' FROM Parties WHERE Name = 'TCS ONLINE SALE ACCOUNT (240-22)'
UNION ALL
SELECT Id, 'NTN', '5555555555' FROM Parties WHERE Name = 'ALI ENTERPRISE (240-1)';