CREATE TABLE Items
(
    Id                    INT              IDENTITY (1,1) PRIMARY KEY,
    OrganizationId        INT              NOT NULL DEFAULT 1,
    Code                  VARCHAR(50)      NOT NULL,
    Name                  VARCHAR(255)     NOT NULL,
    Description           VARCHAR(255)     NULL,
    Pic                   VARCHAR(255)     NULL,
    HSCode                VARCHAR(50)      NULL,   -- Used mainly for inventory / taxable items
    CategoryId            INT              NOT NULL,
    MinQty                DECIMAL(16,2)    NOT NULL DEFAULT 0.00,
    MaxQty                DECIMAL(16,2)    NOT NULL DEFAULT 0.00,
    ReorderQty            DECIMAL(16,2)    NOT NULL DEFAULT 0.00,
    StockType             VARCHAR(50)      NOT NULL DEFAULT 'ITEM',    -- ITEM | SERVICE | FIXED ASSET
    Unit                  VARCHAR(50)      NULL,
    ServingSize           VARCHAR(MAX)     NULL,
    CostPrice             DECIMAL(18,4)    NOT NULL DEFAULT 0.00,
    BasePrice             DECIMAL(18,4)    NOT NULL DEFAULT 0.00,
    DefaultDiscount       DECIMAL(16,6)    NOT NULL DEFAULT 0.00,
    TaxRuleId             INT              NULL,
    ExpenseAccountId      INT              NULL,
    RevenueAccountId      INT              NULL,
    IsFavorite            BIT              NOT NULL DEFAULT 0,
    IsActive              BIT              NOT NULL DEFAULT 1,
    IsSoftDeleted         BIT              NOT NULL DEFAULT 0,
    CreatedBy             INT              NULL,
    CreatedOn             DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CreatedFrom           VARCHAR(255)     NULL,
    UpdatedBy             INT              NULL,
    UpdatedOn             DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedFrom           VARCHAR(255)     NULL,
    CONSTRAINT FK_Items_CreatedBy FOREIGN KEY (CreatedBy) REFERENCES Users(Id),
    CONSTRAINT FK_Items_UpdatedBy FOREIGN KEY (UpdatedBy) REFERENCES Users(Id),
    CONSTRAINT FK_Items_Category FOREIGN KEY (CategoryId) REFERENCES Categories(Id),
    CONSTRAINT FK_Items_Organization FOREIGN KEY (OrganizationId) REFERENCES Organizations(Id),
    CONSTRAINT FK_Items_TaxRule FOREIGN KEY (TaxRuleId) REFERENCES TaxRule(Id),
    CONSTRAINT FK_Items_ExpenseAccount FOREIGN KEY (ExpenseAccountId) REFERENCES ChartOfAccounts(Id),
    CONSTRAINT FK_Items_RevenueAccount FOREIGN KEY (RevenueAccountId) REFERENCES ChartOfAccounts(Id)
);