CREATE TABLE Cashbook
(
    Id                  INT              PRIMARY KEY IDENTITY(1,1),
    OrganizationId      INT             NOT NULL,
    SeqNo               VARCHAR(50)      NOT NULL,
    FileAttachment      VARCHAR(255),
    LocationId          INT,
    PartyId             INT,
    TranDate            DATE             NOT NULL,
    Description         VARCHAR(255)     NOT NULL,
    Amount              DECIMAL(10, 2)   NOT NULL,
    AccountId           INT,
    TranType            VARCHAR(20)      NOT NULL,
    PaymentMethod       VARCHAR(100)     NOT NULL,
    RefNo               VARCHAR(50),
    TranRef             VARCHAR(50),
	CreatedBy           INT             NULL DEFAULT NULL,
	CreatedOn           DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedFrom         VARCHAR(255)    NULL DEFAULT NULL,
	UpdatedBy           INT             NULL DEFAULT NULL,
	UpdatedOn           DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UpdatedFrom         VARCHAR(255)    NULL DEFAULT NULL,
    IsSoftDeleted       SMALLINT         NOT NULL DEFAULT 0,

    FOREIGN KEY (LocationId)   REFERENCES Locations(Id),
    FOREIGN KEY (CreatedBy)    REFERENCES Users(Id),
    FOREIGN KEY (UpdatedBy)    REFERENCES Users(Id),
    FOREIGN KEY (PartyId)      REFERENCES Parties(Id),
    FOREIGN KEY (AccountId)    REFERENCES ChartOfAccounts(Id),
    FOREIGN KEY (OrganizationId)   REFERENCES Organizations(Id)
);
