-- Create PettyCash Table
CREATE TABLE PettyCash
(
    Id                  INT              PRIMARY KEY IDENTITY(1,1),
    OrganizationId      INT             NOT NULL,
    SeqNo               VARCHAR(50)      NOT NULL,
    FileAttachment      VARCHAR(255),
    LocationId          INT,
    PartyId             INT,
    TranDate            DATE             NOT NULL,
    Description         VARCHAR(255)     NOT NULL,
    Amount              DECIMAL(10, 2)   NOT NULL,
    AccountId           INT,
    TranType            VARCHAR(20)      NOT NULL,
    PaymentMethod       VARCHAR(100)     NOT NULL,
    RefNo               VARCHAR(50),
    TranRef             VARCHAR(50),
	CreatedBy           INT             NULL DEFAULT NULL,
	CreatedOn           DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedFrom         VARCHAR(255)    NULL DEFAULT NULL,
	UpdatedBy           INT             NULL DEFAULT NULL,
	UpdatedOn           DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UpdatedFrom         VARCHAR(255)    NULL DEFAULT NULL,
    IsSoftDeleted       SMALLINT         NOT NULL DEFAULT 0,
    IsPostedToGL        SMALLINT         NOT NULL DEFAULT 0,
    PostedToGLDate      DATETIME        NULL,
    PostedToGLBy        INT             NULL,
    GLEntryNo           VARCHAR(50)     NULL,
    Guid                UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    BaseCurrencyId      INT             NULL,
    EnteredCurrencyId   INT             NULL,
    ExchangeRate        DECIMAL(18, 6)  NULL DEFAULT 1.0,
    RowVersion          VARBINARY(8)    NULL,

    FOREIGN KEY (LocationId)   REFERENCES Locations(Id),
    FOREIGN KEY (CreatedBy)    REFERENCES Users(Id),
    FOREIGN KEY (UpdatedBy)    REFERENCES Users(Id),
    FOREIGN KEY (PartyId)      REFERENCES Parties(Id),
    FOREIGN KEY (AccountId)    REFERENCES ChartOfAccounts(Id),
    FOREIGN KEY (OrganizationId)   REFERENCES Organizations(Id),
    FOREIGN KEY (PostedToGLBy)  REFERENCES Users(Id),
    FOREIGN KEY (BaseCurrencyId) REFERENCES Currencies(Id),
    FOREIGN KEY (EnteredCurrencyId) REFERENCES Currencies(Id)
);
