CREATE TABLE Items
(
    Id                    INT              PRIMARY KEY IDENTITY(1,1),
    Guid                  UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    OrganizationId        INT              NOT NULL,
    Pic                   VARCHAR(255)     NULL,
    Code                  VARCHAR(50)      NOT NULL,
    HSCode                VARCHAR(50)      NULL,
    Name                  VARCHAR(255)     NOT NULL,
    Description           VARCHAR(255)     NOT NULL,
    MinQty                DECIMAL(16, 2)   NOT NULL DEFAULT 0.00,
    MaxQty                DECIMAL(16, 2)   NOT NULL DEFAULT 0.00,
    ReOrderQty            DECIMAL(16, 2)   NOT NULL DEFAULT 0.00,
    Discount              DECIMAL(16, 6)   NOT NULL DEFAULT 0.00,
    Tax                   DECIMAL(16, 6)   NOT NULL DEFAULT 0.00,
    CostPrice             DECIMAL(8, 2)    NOT NULL DEFAULT 0.00,
    RetailPrice           DECIMAL(8, 2)    NOT NULL DEFAULT 0.00,
    CategoriesId          INT              NOT NULL,
    StockType             VARCHAR(50)      NULL,
    SaleTypeId            INT              NULL,
    Unit                  VARCHAR(50),
    ServingSize           VARCHAR(MAX),
    IsInventoryItem       INT              DEFAULT 1,
    IsFavItem             INT              DEFAULT 0,
    IsActive              SMALLINT         NOT NULL DEFAULT 1,
    CreatedBy             INT              NULL DEFAULT NULL,
    CreatedOn             DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CreatedFrom           VARCHAR(255)     NULL DEFAULT NULL,
    UpdatedBy             INT              NULL DEFAULT NULL,
    UpdatedOn             DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdatedFrom           VARCHAR(255)     NULL DEFAULT NULL,
    IsSoftDeleted         SMALLINT         NOT NULL DEFAULT 0,
    RowVersion            ROWVERSION,

    FOREIGN KEY (CreatedBy)          REFERENCES Users(Id),
    FOREIGN KEY (UpdatedBy)          REFERENCES Users(Id),
    FOREIGN KEY (CategoriesId)       REFERENCES Categories(Id),
    FOREIGN KEY (OrganizationId)     REFERENCES Organizations(Id),
    FOREIGN KEY (SaleTypeId)         REFERENCES DigitalInvoiceSaleType(Id)
);
