CREATE TABLE Employees
(
    Id               INT IDENTITY(1,1) PRIMARY KEY,
    GUID             UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    OrganizationId   INT NULL,
    EmpId            VARCHAR(25) NOT NULL,
    Fullname         VARCHAR(50) NOT NULL,
    Pic              VARCHAR(2000) NULL,
    Phone            VARCHAR(20) NOT NULL,
    Email            VARCHAR(50) NULL,
    Cnic             VARCHAR(20) NOT NULL,
    EmpAddress       VARCHAR(255) NOT NULL,
    EmpType          VARCHAR(20) NOT NULL,
    EmpDept          VARCHAR(20) NOT NULL,
    LocationId       INT NOT NULL,
    ParentId         INT NOT NULL DEFAULT 0,
    IsActive         SMALLINT NOT NULL DEFAULT 1,
    CreatedBy        INT NULL,
    CreatedOn        DATETIME NOT NULL DEFAULT GETDATE(),
    CreatedFrom      VARCHAR(255) NULL,
    UpdatedBy        INT NULL,
    UpdatedOn        DATETIME NOT NULL DEFAULT GETDATE(),
    UpdatedFrom      VARCHAR(255) NULL,
    IsSoftDeleted    SMALLINT NULL DEFAULT 0,
    RowVersion       ROWVERSION,

    CONSTRAINT FK_Employees_Organization FOREIGN KEY (OrganizationId) REFERENCES Organizations(Id)
);

INSERT INTO Employees (
    OrganizationId,
    EmpId,
    Fullname,
    Pic,
    Phone,
    Email,
    Cnic,
    EmpAddress,
    EmpType,
    EmpDept,
    LocationId,
    ParentId,
    IsActive,
    CreatedBy,
    CreatedFrom,
    UpdatedBy,
    UpdatedFrom,
    IsSoftDeleted
)
VALUES (
    1,
    'EMP00001',
    'AAMIR RASHID',
    NULL,
    '123-456-7890',
    'johndoe@example.com',
    '12345-6789012-3',
    '123 Main St, City, Country',
    'Permanent',
    'HR',
    2,
    0,
    1,
    101,
    '192.168.1.1',
    101,
    '192.168.1.1',
    0
);
