CREATE TABLE acsevent (
    Id                INT PRIMARY KEY AUTO_INCREMENT,
    event_uid         VARCHAR(100) UNIQUE,
    event_time        DATETIME       NOT NULL,
    device_name       VARCHAR(100),
    device_id         VARCHAR(50),
    major             INT,
    minor             INT,
    card_no           VARCHAR(50),
    person_name       VARCHAR(100),
    employee_no       VARCHAR(50),
    departmentid      INT,
    designationid     INT,
    verify_mode       VARCHAR(50),
    picture_url       VARCHAR(255),
    in_out_direction  VARCHAR(5) DEFAULT NULL,
    mask_detected     INT,
    temperature       DECIMAL(4,1),
    reader_id         INT,
    door_no           INT,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
