CREATE TABLE LeaveRequests
(
    Id                  INT IDENTITY(1,1) PRIMARY KEY,
    Guid                UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
    OrganizationId      INT NULL DEFAULT 1,
    EmpId               INT             NOT NULL,
    LeaveTypeId         INT             NOT NULL,
    StartDate           DATE            NOT NULL,
    EndDate             DATE            NOT NULL,
    Reason              VARCHAR(255),
    ContactAddress      VARCHAR(255),
    ContactNumber       VARCHAR(30),
    Status              VARCHAR(15)     DEFAULT 'PENDING',
    AppliedDate         DATETIME        DEFAULT GETDATE(),
    ApprovedBy          INT             NULL,
    ApprovedDate        DATETIME        NULL,
    Remarks             VARCHAR(255)    NULL,
    IsActive            INT             NOT NULL DEFAULT 1,
    CreatedBy           INT             NULL,
    CreatedOn           DATETIME        NOT NULL DEFAULT GETDATE(),
    CreatedFrom         VARCHAR(255)    NULL,
    UpdatedBy           INT             NULL,
    UpdatedOn           DATETIME        NOT NULL DEFAULT GETDATE(),
    UpdatedFrom         VARCHAR(255)    NULL,
    IsSoftDeleted       INT             NULL DEFAULT 0,
    RowVersion          ROWVERSION,

    CONSTRAINT FK_LeaveRequests_EmpId FOREIGN KEY (EmpId) REFERENCES Employees(Id),
    CONSTRAINT FK_LeaveRequests_LeaveType FOREIGN KEY (LeaveTypeId) REFERENCES LeaveTypes(Id),
    CONSTRAINT FK_LeaveRequests_ApprovedBy FOREIGN KEY (ApprovedBy) REFERENCES Employees(Id),
    CONSTRAINT FK_LeaveRequests_Organization FOREIGN KEY (OrganizationId) REFERENCES Organizations(Id)
);
